server:
  port: 22335
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048


mybatis-plus:
  typeAliasesPackage: live.hardproblem.dao.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shiro:
  turns: 1024

logging:
      level:
        root: info
      file:
        name: ./log/log.txt

spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
  thymeleaf:
    prefix: classpath:/static/
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/what_to_eat?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: "root"
    password: "123456"