server:
  port: 22335
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048


mybatis:
  typeAliasesPackage: live.hardproblem.dao.entity
  mapperLocations: classpath:mapper/*.xml

logging:
      level:
        root: info
#  level:
#    live:
#      hardproblem:
#        dao:
#          debug

#    org:
#      springframework:
#        web:
#          servlet:
#            mvc:
#              method:
#                annotation:
#                  RequestMappingHandlerMapping:
#                    trace
      file:
        name: ./log/log.txt

spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
  thymeleaf:
    prefix: classpath:/static/
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/what_to_eat?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: "root"
    password: "123456"